spring.application.name=balance-service
server.port=${PORT:8089}

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (NEON / POSTGRESQL)
# ===============================

spring.datasource.url=${DB_URL:jdbc:postgresql://ep-long-haze-aqga44ke-pooler.c-8.us-east-1.aws.neon.tech/neondb?}
spring.datasource.username=${DB_USER:neondb_owner}
spring.datasource.password=npg_ucXyIqf7T1xw
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=${SHOW_SQL:true}

# CONFIG EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
